lab5/app/__init__.py
import os

from flask import Flask, session, request
from flask_login import current_user
from .dbConnector import db

def create_app(test_config=None):
    app = Flask(__name__, instance_relative_config=False)
    app.config.from_pyfile('config.py', silent=False)

    if test_config:
        app.config.from_mapping(test_config)
    
    db.init_app(app)

    from .cli import init_db_command
    app.cli.add_command(init_db_command)

    from . import auth
    app.register_blueprint(auth.bp)
    auth.login_manager.init_app(app)

    from . import users
    app.register_blueprint(users.bp)
    app.route('/', endpoint='index')(users.index)

    from . import logs
    app.register_blueprint(logs.bp)

    # --- Логирование посещений ---
    @app.before_request
    def log_visit():
        if request.path.startswith('/static') or request.path == '/favicon.ico':
            return

        conn = db.connect()
        cursor = conn.cursor()

        user_id = current_user.get_id()  if current_user.is_authenticated else None # None, если неаутентифицирован
        path = request.path

        try:
            cursor.execute(
                "INSERT INTO visit_logs (path, user_id) VALUES (%s, %s)",
                (path, user_id)
            )
            conn.commit()
        except Exception as e:
            conn.rollback()
            print(f"[log_visit] Ошибка логирования: {e}")
        finally:
            cursor.close()

    return app

lab5/app/auth.py
from functools import wraps
from flask import Blueprint, request, render_template, url_for, flash, redirect
from flask_login import LoginManager, UserMixin, current_user, login_user, logout_user, login_required
from .repositories.user_repository import UserRepository
from .repositories.role_repository import RoleRepository
from .dbConnector import db
from .users import validate_password
import re

user_repository = UserRepository(db)
role_repository = RoleRepository(db)

bp = Blueprint('auth', __name__, url_prefix='/auth')

login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.login_message = 'Для доступа к запрашиваемой странице необходимо пройти процедуру аутенфикации'
login_manager.login_message_category = 'warning'

class User(UserMixin):
    def __init__(self, user_id, username, role_name=None):
        self.id = user_id
        self.user_login = username
        self.role = role_name
        
@login_manager.user_loader
def load_user(user_id):
    user = user_repository.get_by_id(user_id)
    if user is not None:
        role = role_repository.get_by_id(user.role_id) if user.role_id else None
        return User(user.id, user.username, role.name if role else None)
    return None

@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        remember_me = request.form.get('remember_me') == 'on'

        user = user_repository.get_by_username_and_password(username, password)

        if user is not None:
            flash('Вы успешно аутентифицированы', 'success')
            login_user(User(user.id, user.username), remember=remember_me)
            return redirect(request.args.get('next') if request.args.get('next') else url_for('users.index'))
        flash('Неверные данные для аутенфикации.', 'danger')
    return render_template('auth/login.html')

@bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.index'))


# Логика для смены пароля
@bp.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    form_errors = {}

    if request.method == 'POST':
        old_password = request.form['old_password']
        new_password = request.form['new_password']
        confirm_password = request.form['confirm_password']

        # Проверка старого пароля
        username = user_repository.get_by_id(current_user.id).username
        user = user_repository.get_by_username_and_password(username, old_password)
        if not user:
            form_errors['old_password'] = 'Неверный старый пароль.'

        # Проверка нового пароля
        validate_password_result = validate_password(new_password)
        if validate_password_result[0] == False:
            form_errors['new_password'] = validate_password_result[1]
        elif new_password != confirm_password:
            form_errors['confirm_password'] = 'Пароли не совпадают.'

        # Если ошибок нет, сохраняем новый пароль
        if not form_errors:
            # Обновляем пароль пользователя в базе
            user_repository.update_password(current_user.id, new_password)
            flash('Пароль успешно изменён!', 'success')
            return redirect(url_for('users.index'))

        flash('Произошла ошибка при изменении пароля.', 'danger')

    return render_template('auth/change_password.html', form_errors=form_errors)

lab5/app/logs/__init__.py
from flask import Blueprint

bp = Blueprint('logs', __name__, url_prefix='/logs')

from . import routes

lab5/app/logs/routes.py
from flask import render_template, request
from flask_login import login_required, current_user
from . import bp
from ..dbConnector import db
from ..repositories.log_repository import LogRepository
from ..repositories.user_repository import UserRepository

from ..utils.decorators import check_rights

import csv
from io import StringIO
from flask import Response

user_repository = UserRepository(db)

# @bp.route('/')
# @login_required
# def index():
#     repo = LogRepository(db)

#     # Определяем, администратор ли это
#     is_admin = user_repository.get_is_admin_by_id(current_user.id)

#     # Получаем логи: все для админа, только свои для обычных пользователей
#     logs = repo.get_all_with_users(user_id=current_user.id, is_admin=is_admin)
    
#     return render_template('logs/index.html', logs=logs)


@bp.route('/')
@login_required
def index():
    repo = LogRepository(db)
    user_repo = UserRepository(db)

    # Параметры пагинации
    page = int(request.args.get('page', 1))
    per_page = 20
    offset = (page - 1) * per_page

    is_admin = user_repo.get_is_admin_by_id(current_user.get_id())
    logs = repo.get_all_with_users(current_user.get_id(), is_admin, limit=per_page, offset=offset)
    total = repo.count_all(current_user.get_id(), is_admin)

    total_pages = (total + per_page - 1) // per_page

    user_role = user_repo.get_role_name(current_user.get_id())

    return render_template('logs/index.html', logs=logs, page=page, total_pages=total_pages, user_role = user_role)

@bp.route('/by_page')
@login_required
@check_rights('by_page_report')
def report_by_page():
    repo = LogRepository(db)
    
    page_reports = repo.get_by_page()
    return render_template('logs/report_by_page.html', page_reports=page_reports)

@bp.route('/by_user')
@login_required
@check_rights('by_user_report')
def report_by_user():
    repo = LogRepository(db)
    
    user_reports = repo.get_by_users()
    return render_template('logs/report_by_user.html', user_reports=user_reports)


@bp.route('/export/by_page')
@login_required
@check_rights('export_by_page_report')
def export_page_report():
    repo = LogRepository(db)
    data = repo.get_by_page()

    si = StringIO()
    writer = csv.writer(si)
    writer.writerow(['№', 'Страница', 'Количество посещений'])

    for i, row in enumerate(data, start=1):
        writer.writerow([i, row.path, row.visits])

    output = si.getvalue()
    return Response(output, mimetype='text/csv', headers={
        'Content-Disposition': 'attachment; filename=report_by_page.csv'
    })


@bp.route('/export/by_user')
@login_required
@check_rights('export_by_user_report')
def export_user_report():
    repo = LogRepository(db)
    data = repo.get_by_users()

    si = StringIO()
    writer = csv.writer(si)
    writer.writerow(['№', 'Пользователь', 'Количество посещений'])

    for i, row in enumerate(data, start=1):
        if row.first_name:
            name = f"{row.last_name} {row.first_name}"
        else:
            name = "Неаутентифицированный пользователь"
        writer.writerow([i, name, row.visits])

    output = si.getvalue()
    return Response(output, mimetype='text/csv', headers={
        'Content-Disposition': 'attachment; filename=report_by_user.csv'
    })

lab5/app/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">

    <title>
        {% if title %}
          {{ title }}
        {% else %}
          Лабораторная работа №5
        {% endif %}
    </title>
  </head>
  <body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
              <a class="navbar-brand" href="{# url_for('users.index') #}">Лабораторная работа № 5</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{{ url_for('users.index') }}">Main page</a>
                  </li>

                  {% if current_user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Выйти</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.change_password') }}">Сменить пароль</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('logs.index') }}">Логи</a>
                  </li>
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">Войти</a>
                  </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </nav>
    </header>

    <main class="my-3">
      <div class="alerts">
        {% for category, message in get_flashed_messages(True) %}
        <div class="alert alert-{{ category }}" role="alert">
          {{ message }}
        </div>
        {% endfor %}
      </div>
        <div class="container">
            {% block content %}
                <h1>Содержимое по умолчанию</h1>
            {% endblock %}
        </div>

    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <div class="container">
      <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
          <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
            <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
          </a>
          <span class="mb-3 mb-md-0 text-body-secondary">Krupenin Vladimir 231-3210</span>
        </div>
      </footer>
    </div>
  </body>

{% block scripts %}
{% endblock %}

</html>

lab5/app/templates/logs/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Журнал посещений</h1>

{% if current_user.is_authenticated and user_role == 'admin' %}
<p>
    <a href="{{ url_for('logs.report_by_page') }}" class="btn btn-primary">Отчет по страницам</a>
    <a href="{{ url_for('logs.report_by_user') }}" class="btn btn-primary">Отчет по пользователям</a>
</p>
{% endif %}

<table class="table table-bordered">
    <thead>
        <tr>
            <th>№</th>
            <th>Пользователь</th>
            <th>Страница</th>
            <th>Дата</th>
        </tr>
    </thead>
    <tbody>
        {% for log in logs %}
        <tr>
            <td>{{ loop.index + (page - 1) * 20 }}</td>
            <td>{{ log.user_name if log.user_name else "Неаутентифицированный пользователь" }}</td>
            <td>{{ log.path }}</td>
            <td>{{ log.created_at.strftime('%d.%m.%Y %H:%M:%S') }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<!-- Пагинация -->
<nav aria-label="Навигация по страницам">
  <ul class="pagination">
    {% for p in range(1, total_pages + 1) %}
      <li class="page-item {% if p == page %}active{% endif %}">
        <a class="page-link" href="{{ url_for('logs.index') }}?page={{ p }}">{{ p }}</a>
      </li>
    {% endfor %}
  </ul>
</nav>

{% endblock %}

lab5/app/templates/logs/report_by_page.html
{% extends 'base.html' %}

{% block content %}
<h1>Отчёт по посещениям по страницам</h1>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>№</th>
            <th>Страница</th>
            <th>Количество посещений</th>
        </tr>
    </thead>
    <tbody>
        {% for item in page_reports %}
        <tr>
            <td>{{ loop.index }}</td>
            <td>{{ item.path }}</td>
            <td>{{ item.visits }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<a href="{{ url_for('logs.export_page_report') }}" class="btn btn-primary">Экспорт в CSV</a>
{% endblock %}

lab5/app/templates/logs/report_by_user.html
{% extends 'base.html' %}

{% block content %}
<h1>Отчёт по посещениям по пользователям</h1>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>№</th>
            <th>Пользователь</th>
            <th>Количество посещений</th>
        </tr>
    </thead>
    <tbody>
        {% for item in user_reports %}
        <tr>
            <td>{{ loop.index }}</td>
            <td>
                {% if item.first_name %}
                    {{ item.last_name }} {{ item.first_name }}
                {% else %}
                    Неаутентифицированный пользователь
                {% endif %}
            </td>
            <td>{{ item.visits }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<a href="{{ url_for('logs.export_user_report') }}" class="btn btn-primary">Экспорт в CSV</a>
{% endblock %}

lab5/app/templates/users/edit.html
{% extends 'base.html' %}

{% from 'users/form.html' import user_form %}

{% block content %}
<h1 class="mb-3">Изменение пользователя</h1>
{{ user_form(roles, 'edit', user_data, form_errors, current_user) }}
{% endblock %}

lab5/app/templates/users/form.html
{% macro user_form(roles, action, user_data={}, form_errors={}, current_user=None) %}
<form method="post">
    {% macro input_field(name, label, type='text', required=True) %}
        {% set value = user_data[name] or '' %}
        {% set error = form_errors.get(name) %}
        <div class="mb-3 has-validation">
            <label for="{{ name }}" class="form-label">{{ label }}</label>
            <input type="{{ type }}" name="{{ name }}" id="{{ name }}"
                   class="form-control {% if error %}is-invalid{% endif %}"
                   value="{{ value }}"
                   {% if not required %}placeholder="(необязательно)"{% endif %}
                   aria-describedby="{{ name }}-feedback">
            {% if error %}
            <div id="{{ name }}-feedback" class="invalid-feedback">
                {{ error }}
            </div>
            {% endif %}
        </div>
    {% endmacro %}

    {% if action == 'new' %}
        {{ input_field('username', 'Логин') }}
        {{ input_field('password', 'Пароль', 'password') }}
    {% endif %}

    {{ input_field('first_name', 'Имя') }}
    {{ input_field('middle_name', 'Отчество (опционально)', required=False) }}
    {{ input_field('last_name', 'Фамилия') }}

    {% set is_admin = current_user and current_user.role == 'admin' %}
    <div class="mb-3">
        <label for="role_id" class="form-label">Роль</label>
        <select name="role_id" id="role_id" class="form-select" {% if not is_admin %}disabled{% endif %}>
            {% for role in roles %}
            <option value="{{ role.id }}" {% if role.id == user_data.role_id %}selected{% endif %}>
                {{ role.name }}
            </option>
            {% endfor %}
        </select>
        {% if not is_admin %}
            <input type="hidden" name="role_id" value="{{ user_data.role_id }}">
        {% endif %}
    </div>

    <div class="mb-3">
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </div>
</form>
{% endmacro %}

lab5/app/templates/users/index.html
{% extends 'base.html' %}

{% block content %}
<h1 class="my-5">User List</h1>

<table class="table">
    <thead>
        <tr>
            <th>№</th>
            <th>username</th>
            <th>last_name</th>
            <th>first_name</th>
            <th>middle_name</th>
            <th>role</th>
            <th>created_at</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <td>{{ loop.index }}</td>
            <td>{{ user.username }}</td>
            <td>{{ user.last_name }}</td>
            <td>{{ user.first_name }}</td>
            <td>{{ user.middle_name or '' }}</td>
            <td>{{ user.role }}</td>
            <td>{{ user.created_at }}</td>
            <td>
                {% if current_user.role == 'admin' or current_user.id == user.id %}
                    <a class="btn btn-primary" href="{{ url_for('users.show', user_id=user.id) }}">View</a>
                    <a class="btn btn-primary" href="{{ url_for('users.edit', user_id=user.id) }}">Edit</a>
                {% endif %}

                {% if current_user.role == 'admin' %}
                    <button
                        class="btn btn-danger"
                        data-bs-toggle="modal"
                        data-bs-target="#deleteModal"
                        data-user-id="{{ user.id }}"
                        data-user-fullname="{{ user.last_name }} {{ user.first_name }} {{ user.middle_name or '' }}"
                    >
                        Delete
                    </button>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% if current_user.role == 'admin' %}
    <a href="{{ url_for('users.new') }}" class="btn btn-primary">Добавить пользователя</a>
{% endif %}

<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="POST" id="deleteModalForm">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Удаление учётной записи</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                </div>
                <div class="modal-body" id="deleteModalBody">
                    Вы уверены, что хотите удалить пользователя?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Нет</button>
                    <button type="submit" class="btn btn-danger">Да</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='user_delete_modal.js') }}"></script>
{% endblock %}

lab5/app/templates/users/new.html
{% extends 'base.html' %}

{% from 'users/form.html' import user_form %}

{% block content %}
<h1 class="mb-3">Создание нового пользователя</h1>
{{ user_form(roles, 'new', user_data, form_errors, current_user) }}
{% endblock %}

lab5/app/templates/users/show.html
{% extends 'base.html' %}

{% block content %}
<h1>Просмотр учётной записи</h1>
<table class="table">
    <tbody>
        <tr>
            <td>Логин</td>
            <td>{{ user_data.username }}</td>
        </tr>
        <tr>
            <td>Имя</td>
            <td>{{ user_data.first_name }}</td>
        </tr>
        <tr>
            <td>Отчество</td>
            <td>{{ user_data.middle_name or '' }}</td>
        </tr>
        <tr>
            <td>Фамилия</td>
            <td>{{ user_data.last_name }}</td>
        </tr>
        <tr>
            <td>Роль</td>
            <td>{{ user_role }}</td>
        </tr>
        <tr>
            <td>Дата регистрации</td>
            <td>{{ user_data.created_at }}</td>
        </tr>
    </tbody>
</table>
{% endblock %}